// <auto-generated />
using System;
using CamCare.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CamCare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250807131957_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("CamCare.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressType = 1,
                            City = "München",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "1",
                            HouseNumber = "",
                            PostalCode = "80331",
                            Street = "Musterstraße 1"
                        });
                });

            modelBuilder.Entity("CamCare.Domain.Camera", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CameraTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.HasIndex("CameraTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            SerialNumber = "1234567890",
                            CameraTypeId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "1"
                        });
                });

            modelBuilder.Entity("CamCare.Domain.CameraType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CameraTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mini 3000"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mini 3110"
                        },
                        new
                        {
                            Id = 3,
                            Name = "4540"
                        },
                        new
                        {
                            Id = 4,
                            Name = "5030"
                        });
                });

            modelBuilder.Entity("CamCare.Domain.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "max@mustermann.de",
                            FirstName = "Max",
                            LastName = "Mustermann",
                            PhoneNumber = "089190815"
                        });
                });

            modelBuilder.Entity("CamCare.Domain.Defective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Defectives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Display defekt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Objektiv defekt"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Akku defekt"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gehäuse defekt"
                        });
                });

            modelBuilder.Entity("CamCare.Domain.LogisticProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogisticProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefault = true,
                            Name = "DHL"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Dachser"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefault = false,
                            Name = "DPD"
                        });
                });

            modelBuilder.Entity("CamCare.Domain.RepairOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LogisticProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairOrderStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShippingMethod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraSerialNumber");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LogisticProviderId");

                    b.HasIndex("RepairOrderStatusId");

                    b.ToTable("RepairOrders");
                });

            modelBuilder.Entity("CamCare.Domain.RepairOrderRepairPosition", b =>
                {
                    b.Property<int>("RepairOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairPostionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RepairOrderId", "RepairPositionId");

                    b.HasIndex("RepairPositionId");

                    b.ToTable("RepairOrderRepairPosition");
                });

            modelBuilder.Entity("CamCare.Domain.RepairOrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FontColor")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrderClose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RepairOrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColor = "rgb(206, 206, 206)",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reparatur wurde von Kunden angemeldet.",
                            FontColor = "rgb(0, 0, 0)",
                            IsActive = true,
                            IsDefault = true,
                            IsOrderClose = false,
                            Name = "In Anlieferung",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reparatur ist im Lager eingetroffen.",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Eingetroffen",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reparatur wird von Mitarbeiter begutachtet.",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Begutachtung",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            BackgroundColor = "rgb(76, 170, 232)",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Begutachtung wurde vom Mitarbeiter abgeschlosen.",
                            FontColor = "rgb(0, 0, 0)",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Begutachtung abgeschlossen",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Angebot wurde erstellt.",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Angebot erstellt",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kamera befindet sich in der Reparatur.",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Reparatur",
                            Order = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reparatur kann nicht fortgesetzt werden da Ersatzteile bestellt wurden.",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Warte auf Ersatzteile",
                            Order = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kamera ist fertig repariert.",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Reparatur fertig",
                            Order = 8
                        },
                        new
                        {
                            Id = 9,
                            BackgroundColor = "rgb(125, 218, 88)",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kamera wurde versendet.",
                            FontColor = "rgb(0, 0, 0)",
                            IsActive = true,
                            IsDefault = false,
                            IsOrderClose = false,
                            Name = "Versendet",
                            Order = 9
                        });
                });

            modelBuilder.Entity("CamCare.Domain.RepairPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RepairPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Display tauschen",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Artikelnummer = "01532",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Objektiv tauschen",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 3,
                            Artikelnummer = "0153215",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Akku tauschen",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gehäuse tauschen",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("DefectiveRepairOrder", b =>
                {
                    b.Property<int>("DefectivesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepairOrdersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DefectivesId", "RepairOrdersId");

                    b.HasIndex("RepairOrdersId");

                    b.ToTable("DefectiveRepairOrder");
                });

            modelBuilder.Entity("CamCare.Domain.Address", b =>
                {
                    b.HasOne("CamCare.Domain.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CamCare.Domain.Camera", b =>
                {
                    b.HasOne("CamCare.Domain.CameraType", "CameraType")
                        .WithMany("Cameras")
                        .HasForeignKey("CameraTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamCare.Domain.Customer", "Customer")
                        .WithMany("Cameras")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CameraType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CamCare.Domain.RepairOrder", b =>
                {
                    b.HasOne("CamCare.Domain.Camera", "Camera")
                        .WithMany("RepairOrders")
                        .HasForeignKey("CameraSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamCare.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamCare.Domain.LogisticProvider", "LogisticProvider")
                        .WithMany("RepairOrders")
                        .HasForeignKey("LogisticProviderId");

                    b.HasOne("CamCare.Domain.RepairOrderStatus", "RepairOrderStatus")
                        .WithMany()
                        .HasForeignKey("RepairOrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Customer");

                    b.Navigation("LogisticProvider");

                    b.Navigation("RepairOrderStatus");
                });

            modelBuilder.Entity("CamCare.Domain.RepairOrderRepairPosition", b =>
                {
                    b.HasOne("CamCare.Domain.RepairOrder", "RepairOrder")
                        .WithMany("RepairOrderRepairPositions")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamCare.Domain.RepairPosition", "RepairPosition")
                        .WithMany("RepairOrderRepairPositions")
                        .HasForeignKey("RepairPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairOrder");

                    b.Navigation("RepairPosition");
                });

            modelBuilder.Entity("DefectiveRepairOrder", b =>
                {
                    b.HasOne("CamCare.Domain.Defective", null)
                        .WithMany()
                        .HasForeignKey("DefectivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamCare.Domain.RepairOrder", null)
                        .WithMany()
                        .HasForeignKey("RepairOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CamCare.Domain.Camera", b =>
                {
                    b.Navigation("RepairOrders");
                });

            modelBuilder.Entity("CamCare.Domain.CameraType", b =>
                {
                    b.Navigation("Cameras");
                });

            modelBuilder.Entity("CamCare.Domain.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cameras");
                });

            modelBuilder.Entity("CamCare.Domain.LogisticProvider", b =>
                {
                    b.Navigation("RepairOrders");
                });

            modelBuilder.Entity("CamCare.Domain.RepairOrder", b =>
                {
                    b.Navigation("RepairOrderRepairPositions");
                });

            modelBuilder.Entity("CamCare.Domain.RepairPosition", b =>
                {
                    b.Navigation("RepairOrderRepairPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
